#!/bin/bash

# Script to set up secrets in local.properties for GitHub Actions
# This script should be called at the beginning of each GitHub Action workflow

# Ensure the script is run from the repository root
cd "$(dirname "$0")/../.."

# Create or update local.properties file
echo "# This file is auto-generated by GitHub Actions" > local.properties
echo "# Do not edit manually" >> local.properties

# Add the Supabase anon key from GitHub secrets
# The secret is passed as an environment variable from the workflow
if [ -n "$SUPABASE_ANON_KEY" ]; then
  echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> local.properties
  echo "✅ Added SUPABASE_ANON_KEY to local.properties"
else
  echo "❌ SUPABASE_ANON_KEY is not set in GitHub secrets"
  exit 1
fi

# Add any other secrets as needed
# if [ -n "$OTHER_SECRET" ]; then
#   echo "OTHER_SECRET=$OTHER_SECRET" >> local.properties
#   echo "✅ Added OTHER_SECRET to local.properties"
# fi

echo "✅ local.properties has been set up successfully"
