CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, password_hash_salt VARCHAR(255) NOT NULL, email_verified BOOLEAN DEFAULT FALSE NOT NULL, verification_token VARCHAR(255) NULL, reset_token VARCHAR(255) NULL, reset_token_expires_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email);
CREATE TABLE IF NOT EXISTS positions (id BIGSERIAL PRIMARY KEY, fen_representation TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
ALTER TABLE positions ADD CONSTRAINT positions_fen_representation_unique UNIQUE (fen_representation);
CREATE TABLE IF NOT EXISTS moves (id BIGSERIAL PRIMARY KEY, origin BIGINT NOT NULL, destination BIGINT NOT NULL, "name" TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_moves_origin__id FOREIGN KEY (origin) REFERENCES positions(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_moves_destination__id FOREIGN KEY (destination) REFERENCES positions(id) ON DELETE CASCADE ON UPDATE RESTRICT);
ALTER TABLE moves ADD CONSTRAINT moves_origin_name_unique UNIQUE (origin, "name");
ALTER TABLE moves ADD CONSTRAINT moves_origin_destination_unique UNIQUE (origin, destination);
CREATE TABLE IF NOT EXISTS user_positions (id BIGSERIAL PRIMARY KEY, user_id uuid NOT NULL, position_id BIGINT NOT NULL, "depth" INT DEFAULT 0 NOT NULL, last_training_date DATE NOT NULL, next_training_date DATE NOT NULL, is_deleted BOOLEAN DEFAULT FALSE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_user_positions_position_id__id FOREIGN KEY (position_id) REFERENCES positions(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX user_positions_user_id ON user_positions (user_id);
CREATE INDEX user_positions_position_id ON user_positions (position_id);
CREATE INDEX user_positions_next_training_date ON user_positions (next_training_date);
ALTER TABLE user_positions ADD CONSTRAINT user_positions_user_id_position_id_unique UNIQUE (user_id, position_id);
CREATE TABLE IF NOT EXISTS user_moves (id BIGSERIAL PRIMARY KEY, user_id uuid NOT NULL, move_id BIGINT NOT NULL, is_good BOOLEAN DEFAULT TRUE NOT NULL, is_deleted BOOLEAN DEFAULT FALSE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_user_moves_move_id__id FOREIGN KEY (move_id) REFERENCES moves(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX user_moves_user_id ON user_moves (user_id);
CREATE INDEX user_moves_move_id ON user_moves (move_id);
ALTER TABLE user_moves ADD CONSTRAINT user_moves_user_id_move_id_unique UNIQUE (user_id, move_id);
CREATE TABLE IF NOT EXISTS books (id BIGSERIAL PRIMARY KEY, "name" TEXT NOT NULL, downloads BIGINT DEFAULT 0 NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE INDEX books_name ON books ("name");
CREATE INDEX books_downloads ON books (downloads);
CREATE INDEX books_created_at ON books (created_at);
CREATE TABLE IF NOT EXISTS move_cross_book (id BIGSERIAL PRIMARY KEY, move_id BIGINT NOT NULL, book_id BIGINT NOT NULL, is_good BOOLEAN DEFAULT TRUE NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_move_cross_book_move_id__id FOREIGN KEY (move_id) REFERENCES moves(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_move_cross_book_book_id__id FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX move_cross_book_move_id ON move_cross_book (move_id);
CREATE INDEX move_cross_book_book_id ON move_cross_book (book_id);
ALTER TABLE move_cross_book ADD CONSTRAINT move_cross_book_move_id_book_id_unique UNIQUE (move_id, book_id);
CREATE TABLE IF NOT EXISTS downloaded_books (id BIGSERIAL PRIMARY KEY, user_id uuid NOT NULL, book_id BIGINT NOT NULL, downloaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_downloaded_books_book_id__id FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX downloaded_books_user_id ON downloaded_books (user_id);
CREATE INDEX downloaded_books_book_id ON downloaded_books (book_id);
ALTER TABLE downloaded_books ADD CONSTRAINT downloaded_books_user_id_book_id_unique UNIQUE (user_id, book_id);
CREATE TABLE IF NOT EXISTS user_permissions (id BIGSERIAL PRIMARY KEY, user_id uuid NOT NULL, permission VARCHAR(50) NOT NULL, granted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE INDEX user_permissions_user_id ON user_permissions (user_id);
ALTER TABLE user_permissions ADD CONSTRAINT user_permissions_user_id_permission_unique UNIQUE (user_id, permission);
CREATE SEQUENCE IF NOT EXISTS positions_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS moves_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS user_positions_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS user_moves_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS books_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS move_cross_book_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS downloaded_books_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS user_permissions_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
